### ISSUE TITLE
Ticks and Crosses do not appear correctly in downloadable PDF

### ISSUE THREAD

**Issue by sgparry** [Kury25/moodle-assignfeedback_editpdfplus#14]
If you use symbols such as ticks and crosses in stamps, they appear as question marks in the final downloadable PDF file. I have attached a simple example.
[ThisIsATest.pdf](https://github.com/Kury25/moodle-assignfeedback_editpdfplus/files/2974977/ThisIsATest.pdf)

**Comment by Kury25** [comment]
Hello, and thanks for your feedback.
It is indeed a problem already identified. (-- However, I do not have any anomalies in your pdf file. --)
The PHP generation library PDF is too old to support these new characters and special fonts.
I am looking for a newer engine to overcome this problem among others. It is a big job to modify the integration of this library, I think I take advantage of the adaptation of the plugin to Moodle 3.7 to perform this operation.

**Comment by Kury25** [comment]
resolved in d84bac8c586b3867dfb40c986da894c22898922f
