### ISSUE TITLE
Strings HARDCODE

### ISSUE THREAD

**Issue by dinism** [Kury25/moodle-assignfeedback_editpdfplus#17]
I'm a PT-PT translator in AMOS.
Some strings in the plugin are hardcoded. Is it possible to translate them?
THXS
![imagem](https://user-images.githubusercontent.com/14828021/59774460-66004c00-92a7-11e9-8f6f-1dc468df5c2d.png)

**Comment by Kury25** [comment]
Of course. I will publish it soon

**Comment by dinism** [comment]
Here are others issues.
![imagem](https://user-images.githubusercontent.com/14828021/59777460-9c8c9580-92ac-11e9-9712-57a6f67cd52b.png)

![imagem](https://user-images.githubusercontent.com/14828021/59777486-ad3d0b80-92ac-11e9-976c-a7364f628c9e.png)

![imagem](https://user-images.githubusercontent.com/14828021/59777506-b62ddd00-92ac-11e9-8cbb-ce2ba57abe7e.png)

**Comment by Kury25** [comment]
"tool saved" is not hardcoded: see adminedittool_messageok

**Comment by Kury25** [comment]
solve in commit c39e0ad50b58b5c1f9c331114e7c7ea34937bb3e
