### ISSUE TITLE
No need to include french language strings in ZIP file

### ISSUE THREAD

**Issue by germanvaleroelizondo** [Kury25/moodle-assignfeedback_editpdfplus#2]
Hi,

Nowadays there is no need to include language files for languages other than English inside the plugin downloadable ZIP file. Please read https://lang.moodle.org/mod/forum/discuss.php?d=2485 .

I have already sent them to the AMOS french language maintainers and, if accepted,  should soon be incorporated into the franch language pack. I will write you when they do, so that you can then remove them from here.

Thanks in advance

**Comment by germanvaleroelizondo** [comment]
OOps,
The fr language file included many untranslated English strings.

I will re-submit the file without the english texts as soon as AMOS is back on line

![moodle_org is down](https://user-images.githubusercontent.com/2671923/45430168-61e53500-b66a-11e8-8b55-4d88a5782aeb.png)


[assignfeedback_editpdfplus.zip](https://github.com/Kury25/moodle-assignfeedback_editpdfplus/files/2375473/assignfeedback_editpdfplus.zip)

**Comment by ndunand** [comment]
Thanks @germanvaleroelizondo ,

While this is corrected in the plugin, I've pushed the missing lang strings to AMOS. They'll be made available once Nicolas Martignoni validates them.

**Comment by martignoni** [comment]
Thanks @ndunand. I've just committed the new strings to AMOS.

**Comment by ndunand** [comment]
Merci @martignoni 😊

**Comment by germanvaleroelizondo** [comment]
You can now safely remove the fr translation from the files included in the downloadable ZIP file for this plugin.

**Comment by ndunand** [comment]
Fixed by 2b4cc7c
