### ISSUE TITLE
Error restoring course assignment from Recycle Bin

### ISSUE THREAD

**Issue by zulaxia** [Kury25/moodle-assignfeedback_editpdfplus#20]
Restoring a course assignment throws the following, which looks like it's this plugin not having a restore method defined?

Restore method process_assignfeedback_editpdfplus_feedback_editpdfplus_pagerotation is missing. It must be defined by a developer.

**Comment by zulaxia** [comment]
Debug info:
Error code: restore_path_element_missingmethod

×Stack trace:
line 83 of /backup/util/structure/restore_path_element.class.php: restore_path_element_exception thrown
line 91 of /backup/util/structure/restore_path_element.class.php: call to restore_path_element->validate_pobject()
line 65 of /backup/moodle2/restore_subplugin.class.php: call to restore_path_element->set_processing_object()
line 366 of /backup/util/plan/restore_structure_step.class.php: call to restore_subplugin->define_subplugin_structure()
line 64 of /mod/assign/backup/moodle2/restore_assign_stepslib.php: call to restore_structure_step->add_subplugin_structure()
line 84 of /backup/util/plan/restore_structure_step.class.php: call to restore_assign_activity_structure_step->define_structure()
line 181 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
line 210 of /backup/moodle2/restore_activity_task.class.php: call to base_task->execute()
line 178 of /backup/util/plan/base_plan.class.php: call to restore_activity_task->execute()
line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 377 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 264 of /admin/tool/recyclebin/classes/course_bin.php: call to restore_controller->execute_plan()
line 101 of /admin/tool/recyclebin/index.php: call to tool_recyclebin\course_bin->restore_item()

**Comment by ndunand** [comment]
This should be fixed in the lastest released, published today.
